name: vtbench
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0
  - torchvision>=0.15
  - pytorch-cuda=12.1
  - numpy
  - scikit-learn
  - matplotlib
  - pyyaml
  - pillow
  - pip
  - pip:
    - imbalanced-learn
